/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit typed final answers for deterministic marking */
        post: operations["submitPracticeAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_key}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated learner's safe course map */
        get: operations["getCourseMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check learning API availability */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated learner progress and the recommended next action */
        get: operations["getLearningHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an authenticated learner-safe lesson revision */
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_key}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Idempotently start a lesson for the authenticated learner */
        post: operations["startLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated learner profile and pinned enrolments */
        get: operations["getCurrentLearner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a beta invitation and pin the learner to its course revision */
        post: operations["acceptBetaInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start or replay an idempotent learner-owned practice session */
        post: operations["createPracticeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume an owned practice session */
        get: operations["getPracticeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get or assign the next question in an owned session */
        get: operations["getNextPracticeQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/questions/{question_key}/give-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock the authored solution after two incorrect attempts */
        post: operations["giveUpPracticeQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/questions/{question_key}/hints/{stage}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal the next authored hint in an owned session */
        post: operations["revealPracticeHint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated learner progress across the N1 course */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitationRequest */
        AcceptInvitationRequest: {
            /** Display Name */
            display_name: string;
            /** Invitation Code */
            invitation_code: string;
        };
        /** AttemptPartResult */
        AttemptPartResult: {
            /** Correct */
            correct: boolean;
            /** Error */
            error: string | null;
            /** Marks Available */
            marks_available: number;
            /** Marks Awarded */
            marks_awarded: number;
            /** Position */
            position: number;
        };
        /** AttemptResponse */
        AttemptResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Correct */
            correct: boolean;
            /** Marks Available */
            marks_available: number;
            /** Marks Awarded */
            marks_awarded: number;
            /** Parts */
            parts: components["schemas"]["AttemptPartResult"][];
            /** Question Finished */
            question_finished: boolean;
            /** Solution Available */
            solution_available: boolean;
        };
        /** CourseLessonMap */
        CourseLessonMap: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "content_pending" | "available";
            /**
             * Content Status
             * @enum {string}
             */
            content_status: "draft" | "reviewed" | "published" | "retired";
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Href */
            href: string;
            /**
             * Learning Material State
             * @enum {string}
             */
            learning_material_state: "pending" | "ready";
            /** Objectives */
            objectives: string[];
            /** Outcomes */
            outcomes: string[];
            /** Position */
            position: number;
            /**
             * Progress State
             * @default not_started
             * @enum {string}
             */
            progress_state: "not_started" | "in_progress" | "practice_completed" | "proficient" | "mastered";
            /** Required Practice Count */
            required_practice_count: number;
            /** Stable Key */
            stable_key: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** CourseMapResponse */
        CourseMapResponse: {
            /**
             * Content Status
             * @enum {string}
             */
            content_status: "draft" | "reviewed" | "published" | "retired";
            /** Description */
            description: string;
            /** Development Preview */
            development_preview: boolean;
            /** Revision */
            revision: number;
            /** School Level */
            school_level: string;
            /** Stable Key */
            stable_key: string;
            /** Subject */
            subject: string;
            /** Title */
            title: string;
            /** Units */
            units: components["schemas"]["CourseUnitMap"][];
        };
        /** CourseUnitMap */
        CourseUnitMap: {
            /** Checkpoint Available */
            checkpoint_available: boolean;
            /** Checkpoint Question Count */
            checkpoint_question_count: number;
            /** Lessons */
            lessons: components["schemas"]["CourseLessonMap"][];
            /** Position */
            position: number;
            /** Stable Key */
            stable_key: string;
            /** Title */
            title: string;
        };
        /** CreatePracticeSessionRequest */
        CreatePracticeSessionRequest: {
            /** Lesson Key */
            lesson_key: string;
            /**
             * Mode
             * @default guided_practice
             * @constant
             */
            mode: "guided_practice";
            /** Question Count */
            question_count?: number | null;
        };
        /** CurrentLearnerResponse */
        CurrentLearnerResponse: {
            /** Enrolments */
            enrolments: components["schemas"]["EnrolmentResponse"][];
            profile: components["schemas"]["ProfileResponse"];
        };
        /** EnrolmentResponse */
        EnrolmentResponse: {
            /** Course Key */
            course_key: string;
            /** Course Revision */
            course_revision: number;
            /**
             * Enrolled At
             * Format: date-time
             */
            enrolled_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "withdrawn";
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** GiveUpResponse */
        GiveUpResponse: {
            solution: components["schemas"]["SolutionResponse"];
            /**
             * Status
             * @constant
             */
            status: "gave_up";
        };
        /** HealthDependencies */
        HealthDependencies: {
            /**
             * Authentication
             * @default supabase_bearer
             * @constant
             */
            authentication: "supabase_bearer";
            /**
             * Course Content
             * @default draft_placeholders
             * @constant
             */
            course_content: "draft_placeholders";
            /**
             * Tutor
             * @default disabled
             * @constant
             */
            tutor: "disabled";
        };
        /** HealthResponse */
        HealthResponse: {
            dependencies?: components["schemas"]["HealthDependencies"];
            /** Environment */
            environment: string;
            /** Request Id */
            request_id: string;
            /**
             * Service
             * @default learning-api
             * @constant
             */
            service: "learning-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HintPartResponse */
        HintPartResponse: {
            /** Content */
            content: {
                [key: string]: unknown;
            }[];
            /** Position */
            position: number;
        };
        /** HintResponse */
        HintResponse: {
            /** Parts */
            parts: components["schemas"]["HintPartResponse"][];
            /**
             * Stage
             * @enum {integer}
             */
            stage: 1 | 2;
        };
        /** InvitationAcceptanceResponse */
        InvitationAcceptanceResponse: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
            /** Enrolments */
            enrolments: components["schemas"]["EnrolmentResponse"][];
            profile: components["schemas"]["ProfileResponse"];
        };
        /** LearningHomeResponse */
        LearningHomeResponse: {
            /** Course Key */
            course_key: string;
            /** Learner Id */
            learner_id: string;
            /** Lessons */
            lessons: components["schemas"]["LessonProgressResponse"][];
            next_action: components["schemas"]["NextActionResponse"];
            /** Unresolved Retry Count */
            unresolved_retry_count: number;
        };
        /** LessonProgressResponse */
        LessonProgressResponse: {
            /**
             * Checkpoint Passed
             * @default false
             */
            checkpoint_passed: boolean;
            /**
             * Correct Count
             * @default 0
             */
            correct_count: number;
            /**
             * Eventual Correct Percentage
             * @default 0
             */
            eventual_correct_percentage: number;
            /**
             * Gave Up Count
             * @default 0
             */
            gave_up_count: number;
            /** Last Session Id */
            last_session_id?: string | null;
            /** Lesson Key */
            lesson_key: string;
            /** Lesson Title */
            lesson_title: string;
            /** Position */
            position: number;
            /**
             * Question Count
             * @default 0
             */
            question_count: number;
            /**
             * Resolved Count
             * @default 0
             */
            resolved_count: number;
            /**
             * State
             * @enum {string}
             */
            state: "not_started" | "in_progress" | "practice_completed" | "proficient" | "mastered";
            /** Updated At */
            updated_at?: string | null;
        };
        /** LessonResponse */
        LessonResponse: {
            /** Assets */
            assets: {
                [key: string]: unknown;
            }[];
            /**
             * Content Status
             * @enum {string}
             */
            content_status: "draft" | "reviewed" | "published" | "retired";
            /** Course Key */
            course_key: string;
            /** Development Preview */
            development_preview: boolean;
            /** Estimated Minutes */
            estimated_minutes: number;
            /**
             * Learning Material State
             * @enum {string}
             */
            learning_material_state: "pending" | "ready";
            /** Objectives */
            objectives: string[];
            /** Outcomes */
            outcomes: string[];
            /** Position */
            position: number;
            practice: components["schemas"]["PracticeEntry"];
            /** Revision */
            revision: number;
            /** Sections */
            sections: {
                [key: string]: unknown;
            }[];
            /** Stable Key */
            stable_key: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Unit Key */
            unit_key: string;
        };
        /** NextActionResponse */
        NextActionResponse: {
            /** Description */
            description: string;
            /** Href */
            href: string;
            /** Lesson Key */
            lesson_key?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "start_lesson" | "resume_practice" | "retry_practice" | "continue_lesson" | "content_pending" | "checkpoint_pending";
        };
        /** NextQuestionResponse */
        NextQuestionResponse: {
            /** Attempt Count */
            attempt_count?: number | null;
            /** Highest Hint Stage */
            highest_hint_stage?: number | null;
            /** Position */
            position?: number | null;
            question?: components["schemas"]["PublicQuestionResponse"] | null;
            /** Selection Reason */
            selection_reason?: string | null;
            session: components["schemas"]["PracticeSessionSummary"];
            /** Solution Available */
            solution_available?: boolean | null;
            /** Stage */
            stage?: ("guided" | "independent" | "challenge") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed";
        };
        /** PracticeEntry */
        PracticeEntry: {
            /** Available */
            available: boolean;
            /**
             * Development Available
             * @default false
             */
            development_available: boolean;
            /** Lesson Key */
            lesson_key: string;
            /**
             * Mode
             * @default guided_practice
             * @constant
             */
            mode: "guided_practice";
            /** Question Count */
            question_count: number;
            /** Unavailable Reason */
            unavailable_reason?: ("content_not_reviewed" | "questions_not_published") | null;
        };
        /** PracticeSessionResponse */
        PracticeSessionResponse: {
            /** Development Drafts */
            development_drafts: boolean;
            /** Lesson Key */
            lesson_key: string;
            /**
             * Mode
             * @constant
             */
            mode: "guided_practice";
            /** Question Count */
            question_count: number;
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed";
        };
        /** PracticeSessionSummary */
        PracticeSessionSummary: {
            /** Assigned Count */
            assigned_count: number;
            /** Correct Count */
            correct_count: number;
            /** Development Drafts */
            development_drafts: boolean;
            /** Gave Up Count */
            gave_up_count: number;
            /** Lesson Key */
            lesson_key: string;
            /**
             * Mode
             * @constant
             */
            mode: "guided_practice";
            /** Question Count */
            question_count: number;
            /** Resolved Count */
            resolved_count: number;
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed";
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /** Learner Id */
            learner_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "content_admin" | "academic_admin";
            /** Target Track */
            target_track: string | null;
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Checkpoint Required For Mastery */
            checkpoint_required_for_mastery: boolean;
            /** Course Key */
            course_key: string;
            /** Learner Id */
            learner_id: string;
            /** Lessons */
            lessons: components["schemas"]["LessonProgressResponse"][];
            /** Proficiency Threshold */
            proficiency_threshold: number;
        };
        /** PublicQuestionResponse */
        PublicQuestionResponse: {
            /** Assets */
            assets: components["schemas"]["QuestionAssetResponse"][];
            /** Calculator Allowed */
            calculator_allowed: boolean;
            /** Difficulty */
            difficulty: number;
            /** Parts */
            parts: components["schemas"]["QuestionPartResponse"][];
            /** Primary Outcome */
            primary_outcome: string;
            /** Revision */
            revision: number;
            /**
             * Source Status
             * @enum {string}
             */
            source_status: "draft" | "reviewed" | "published" | "retired";
            /** Stable Key */
            stable_key: string;
            /** Stem */
            stem: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
            /** Total Marks */
            total_marks: number;
        };
        /** QuestionAssetResponse */
        QuestionAssetResponse: {
            /** Alt Text */
            alt_text: string;
            /** Asset Key */
            asset_key: string;
            /** Format */
            format: string;
            /** Height */
            height: number | null;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
            /** Width */
            width: number | null;
        };
        /** QuestionPartResponse */
        QuestionPartResponse: {
            /** Input Placeholder */
            input_placeholder: string;
            /** Label */
            label: string | null;
            /** Marks */
            marks: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: {
                [key: string]: unknown;
            }[];
            /**
             * Response Type
             * @enum {string}
             */
            response_type: "numeric" | "algebraic_expression";
        };
        /** SolutionPartResponse */
        SolutionPartResponse: {
            /** Canonical Answer */
            canonical_answer: string;
            /** Canonical Latex */
            canonical_latex: string;
            /** Label */
            label: string | null;
            /** Position */
            position: number;
            /** Steps */
            steps: {
                [key: string]: unknown;
            }[];
        };
        /** SolutionResponse */
        SolutionResponse: {
            /** Parts */
            parts: components["schemas"]["SolutionPartResponse"][];
            /** Revision */
            revision: number;
            /** Stable Key */
            stable_key: string;
        };
        /** SubmitAttemptRequest */
        SubmitAttemptRequest: {
            /** Answers */
            answers: {
                [key: string]: string;
            };
            /** Question Key */
            question_key: string;
            /** Question Revision */
            question_revision: number;
            /** Session Id */
            session_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submitPracticeAttempt: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCourseMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseMapResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getLearningHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningHomeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    startLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonProgressResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCurrentLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentLearnerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    acceptBetaInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAcceptanceResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createPracticeSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getPracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionSummary"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getNextPracticeQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextQuestionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    giveUpPracticeQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                question_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiveUpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    revealPracticeHint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                question_key: string;
                stage: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
