"""Create the ignored local API environment without exposing database credentials."""

from __future__ import annotations

import getpass
import os
from pathlib import Path
from urllib.parse import quote, unquote, urlsplit, urlunsplit

import psycopg

from learning_api.config import REQUIRED_SCHEMA_REVISION

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
WEB_ENV = REPOSITORY_ROOT / "apps/web/.env.local"
API_ENV = REPOSITORY_ROOT / "services/learning_api/.env.local"
POOLER_URL = REPOSITORY_ROOT / "supabase/.temp/pooler-url"


def _read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        if line.startswith("export "):
            line = line.removeprefix("export ").lstrip()
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[key.strip()] = value
    return values


def _database_url(pooler_url: str, password: str) -> str:
    parsed = urlsplit(pooler_url)
    if (
        parsed.scheme not in {"postgres", "postgresql"}
        or not parsed.hostname
        or not parsed.username
    ):
        raise SystemExit("The linked Supabase pooler URL is invalid. Link the project again.")
    username = quote(unquote(parsed.username), safe="")
    encoded_password = quote(password, safe="")
    host = parsed.hostname
    port = f":{parsed.port}" if parsed.port else ""
    return urlunsplit(
        ("postgresql", f"{username}:{encoded_password}@{host}{port}", parsed.path, parsed.query, "")
    )


def _check_database(database_url: str) -> bool:
    try:
        with psycopg.connect(database_url, connect_timeout=15) as connection:
            connection.execute("select 1").fetchone()
            row = connection.execute(
                """
                select exists (
                    select 1
                    from supabase_migrations.schema_migrations
                    where version = %s
                )
                """,
                (REQUIRED_SCHEMA_REVISION,),
            ).fetchone()
            return bool(row and row[0])
    except psycopg.Error as exc:
        if exc.sqlstate == "28P01":
            raise SystemExit(
                "Supabase rejected the project database password (SQLSTATE 28P01). "
                "The linked shared-pooler username is correct. Reset the database "
                "password under Supabase Dashboard > Database > Settings, wait briefly "
                "for the pooler to update, and run this command once more."
            ) from exc
        message = str(exc).splitlines()[0] if str(exc) else exc.__class__.__name__
        raise SystemExit(f"Could not connect to Supabase PostgreSQL: {message}") from exc


def main() -> None:
    web_values = _read_env(WEB_ENV)
    supabase_url = web_values.get("NEXT_PUBLIC_SUPABASE_URL", "").strip()
    publishable_key = web_values.get("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "").strip()
    if not supabase_url or not publishable_key:
        raise SystemExit(
            "Configure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "
            "in apps/web/.env.local first."
        )
    if not POOLER_URL.exists():
        raise SystemExit(
            "No linked Supabase project was found. Run corepack pnpm dlx supabase@latest link "
            "--project-ref YOUR_PROJECT_REF first."
        )

    password = os.getenv("SUPABASE_DB_PASSWORD") or getpass.getpass(
        "Supabase database password (input is hidden): "
    )
    if not password:
        raise SystemExit("A database password is required.")
    database_url = _database_url(POOLER_URL.read_text(encoding="utf-8").strip(), password)
    schema_current = _check_database(database_url)

    contents = "\n".join(
        [
            "# Generated by corepack pnpm setup:api; this file is git-ignored.",
            "ASEAN_ACADEMY_ENV=development",
            f"ASEAN_ACADEMY_DATABASE_URL={database_url}",
            f"ASEAN_ACADEMY_REPOSITORY_ROOT={REPOSITORY_ROOT}",
            "ASEAN_ACADEMY_ALLOW_DRAFT_CONTENT=true",
            "ASEAN_ACADEMY_CORS_ORIGINS=http://localhost:3000",
            f"SUPABASE_URL={supabase_url}",
            f"SUPABASE_ANON_KEY={publishable_key}",
            "SUPABASE_JWT_AUDIENCE=authenticated",
            "",
        ]
    )
    API_ENV.write_text(contents, encoding="utf-8")
    API_ENV.chmod(0o600)
    print(f"Saved local API configuration to {API_ENV.relative_to(REPOSITORY_ROOT)}.")
    if schema_current:
        print(f"Supabase schema revision {REQUIRED_SCHEMA_REVISION} is present.")
    else:
        print(
            f"Warning: migration {REQUIRED_SCHEMA_REVISION} is not present yet. "
            "Apply pending migrations before testing lesson progress."
        )
    print("Restart the API with corepack pnpm dev:api.")


if __name__ == "__main__":
    main()
